### ISSUE TITLE
Remapping keys

### ISSUE THREAD

**Issue by JasonJAyalaP** [kana/vim-textobj-entire#2]
Hi. I love your text object enhancements, but I'm a little confused about how to remap the keys. I don't mind the defaults, but I think it's more memorable to use `ab` and `ib` (b for buffer instead of e for entire). However, I can't figure out what the doc is saying when it talks about `:TextobjEntireDefaultKeyMappings`, and simply:

``` vim
map ib (textobj-entire-i)
```

doesn't work.

Thanks.

---

**_Edit**_ After reading your response of RTFM here: https://github.com/kana/vim-textobj-indent/issues/4 I'd rather not bother.

**Comment by einar-io** [comment]
I am confused too. I use both `textobj-entire` and `textobj-latex`. Both bind `ae` and `ie`, but right now the former overwrites the latter's bindings.

With the previous post I can _also_ map `ab` and `ib` to `textobj-entire`, but then how do I remove it's previous bindings to `ae` and `ie`, so they are bound to `textobj-latex`?
