### ISSUE TITLE
py3 vim.eval('g:') raises UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by gyermolenko** [kana/vim-textobj-entire#5]
related to [https://github.com/Valloric/YouCompleteMe/issues/2127](https://github.com/Valloric/YouCompleteMe/issues/2127)

**Comment by gyermolenko** [comment]
":echo g: " prints the following (just the part with suspicious symbols):
'__textobj_entire': {'obj_specs': {'-': {'select-i-function': '<80><fd>Q89_select_i', 'select-a': ['ae'], 'sfile': '/home/gy/.vim/bundle/vim-textobj-entire/plugin/textobj/entire.vim', 'select-a-function': '<80><fd>Q89_select_a', 'select-i': ['ie']}}

**Comment by kana** [comment]
Strings in Vim script can contain arbitrary bytes which might not be legal UTF-8 byte sequences.  But YouCompleteMe did expect all strings are legal UTF-8 byte sequences.
