### ISSUE TITLE
Mark ' not set with cursor's column

### ISSUE THREAD

**Issue by Asheq** [kana/vim-textobj-entire#8]
In https://github.com/kana/vim-textobj-entire/blob/master/plugin/textobj/entire.vim on line 57:

    mark  '

This sets the mark using column 0 instead of the cursor's column (see `:help :mark`). So after `yae`, a `<C-o>` or \`\`  returns you to the correct line, but incorrect column. I would recommend replacing line 57 with the following, which sets the mark using the cursor's column:

    normal m'

(There might be a different way to do this as well without using normal but I haven't found it).

**Comment by kana** [comment]
Thank you for the report. I've fixed the problem.
